app/models/cpu.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class CPU(db.Model):
    __tablename__ = "cpu"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    percents = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<CPU {self.id}>"

app/models/disk.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class Disk(db.Model):
    __tablename__ = "disk"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    mount_point = db.Column(db.String(20), nullable=False)
    total = db.Column(db.String(20), nullable=False)
    used = db.Column(db.String(20), nullable=False)
    free = db.Column(db.String(20), nullable=False)
    percent = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f"<Disk {self.id}>"

app/models/memory.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class Memory(db.Model):
    __tablename__ = "memory"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    active = db.Column(db.String(20), nullable=False)
    available = db.Column(db.String(20), nullable=False)
    free = db.Column(db.String(20), nullable=False)
    inactive = db.Column(db.String(20), nullable=False)
    percent = db.Column(db.Integer, nullable=False)
    total = db.Column(db.String(20), nullable=False)
    used = db.Column(db.String(20), nullable=False)
    wired = db.Column(db.String(20), nullable=False)

    def __repr__(self):
        return f"<Memory {self.id}>"

app/models/network.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class NetworkInfo(db.Model):
    __tablename__ = "network_info"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    bytes_sent = db.Column(db.String(20), nullable=False)
    bytes_recvd = db.Column(db.String(20), nullable=False)
    packets_sent = db.Column(db.String(20), nullable=False)
    packets_recvd = db.Column(db.String(20), nullable=False)
    err_pkt_in = db.Column(db.String(20), nullable=False)
    err_pkt_out = db.Column(db.String(20), nullable=False)
    dropped_pkt_in = db.Column(db.String(20), nullable=False)
    dropped_pkt_out = db.Column(db.String(20), nullable=False)

    def __repr__(self):
        return f"<NetworkInfo {self.id}>"


class NetworkIp(db.Model):
    __tablename__ = "network_ips"

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    addresses = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<NetworkIp {self.id}>"

app/models/reports.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class UserReports(db.Model):
    __tablename__ = "user_reports"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    report_id = db.Column(db.String(36), nullable=False)
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"))
    timestamp = db.Column(db.DateTime, nullable=False)
    email = db.Column(db.String(255), nullable=False)
    target = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<UserReports {self.id}>"

app/models/system.py
#!/usr/bin/env python3

import uuid

from app.extensions import db


class SystemUser(db.Model):
    __tablename__ = "system_users"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    started = db.Column(db.DateTime, nullable=False)
    terminal = db.Column(db.String(255), nullable=False)
    username = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<SystemUser {self.id}>"


class SystemUptime(db.Model):
    __tablename__ = "system_uptime"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    uptime = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<SystemUptime {self.id}>"


class SystemOper(db.Model):
    __tablename__ = "operating_system"

    id = db.Column(db.String(36), default=lambda: str(uuid.uuid4()), primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    report_id = db.Column(db.String(36), nullable=False)
    target = db.Column(db.String(255), nullable=False)
    opersys = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return f"<SystemOper {self.id}>"

app/blueprints.py
#!/usr/bin/env python3

from flask import request
from flask import Blueprint
from flask import render_template
from flask import abort

from app.extensions import db
from app.models.memory import Memory
from app.models.cpu import CPU
from app.models.disk import Disk
from app.models.process import Process
from app.models.reports import UserReports
from app.models.network import NetworkInfo, NetworkIp
from app.models.system import SystemUser, SystemUptime, SystemOper


BasePrint = Blueprint("base_print", __name__)


@BasePrint.route("/", methods=["GET"])
def home():
    return render_template("index.html", title="Home"), 200


@BasePrint.route("/reports", methods=["GET"])
def reports():
    reports = UserReports.query.all()

    return render_template("reports.html", title="Reports", reports=reports), 200


@BasePrint.route("/memory", methods=["GET"])
def memory():
    memory_stats = Memory.query.all()
    return (
        render_template("memory.html", title="Memory", memory_stats=memory_stats),
        200,
    )


@BasePrint.route("/cpu", methods=["GET"])
def cpu():
    cpu_stats = CPU.query.all()
    return render_template("cpu.html", title="CPU", cpu_stats=cpu_stats), 200


@BasePrint.route("/disk", methods=["GET"])
def disk():
    disk_stats = Disk.query.all()
    return render_template("disk.html", title="Disk", disk_stats=disk_stats), 200


@BasePrint.route("/network", methods=["GET"])
def network():
    network_stats = NetworkInfo.query.all()
    network_ips = NetworkIp.query.all()

    return (
        render_template(
            "network.html",
            title="Network",
            network_stats=network_stats,
            network_ips=network_ips,
        ),
        200,
    )


@BasePrint.route("/system", methods=["GET"])
def system():
    system_users = SystemUser.query.all()
    system_uptime = SystemUptime.query.all()
    system_os = SystemOper.query.all()

    return (
        render_template(
            "system.html",
            title="System",
            system_users=system_users,
            system_uptime=system_uptime,
            system_os=system_os,
        ),
        200,
    )


@BasePrint.route("/report/details", methods=["GET"])
def report_details():
    report_id = request.args["report_id"]

    user_report = UserReports.query.filter_by(report_id=report_id).first()
    if not user_report:
        return abort(404)

    disk_data = Disk.query.filter_by(report_id=report_id).all()
    cpu_data = CPU.query.filter_by(report_id=report_id).all()
    memory_data = Memory.query.filter_by(report_id=report_id).all()
    network_info_data = NetworkInfo.query.filter_by(report_id=report_id).all()
    network_ip_data = NetworkIp.query.filter_by(report_id=report_id).all()
    system_uptime_data = SystemUptime.query.filter_by(report_id=report_id).all()
    system_user_data = SystemUser.query.filter_by(report_id=report_id).all()
    system_os_data = SystemOper.query.filter_by(report_id=report_id).all()
    process_data = Process.query.filter_by(report_id=report_id).all()

    return (
        render_template(
            "report_details.html",
            title="Report Details",
            disk_data=disk_data,
            cpu_data=cpu_data,
            memory_data=memory_data,
            network_info_data=network_info_data,
            network_ip_data=network_ip_data,
            system_uptime_data=system_uptime_data,
            system_user_data=system_user_data,
            system_os_data=system_os_data,
            process_data=process_data,
        ),
        200,
    )

app/templates/cpu.html
{% extends "index.html" %}
{% block content %}
<h1>Agent CPU Information</h1>
<table>
    <thead>
       <tr>
         <th>ID</th> 
         <th>Timestamp</th>
         <th>Report ID</th>
         <th>Target</th>
         <th>Percents</th>
       </tr>
    </thead>
    
    <tbody>
       {% for row in cpu_stats %}
          <tr>
             <td>{{ row.id }}</td> 
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.percents }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
{% endblock %}

app/templates/disk.html
{% extends "index.html" %}
{% block content %}
<h1>Agent Disk Information</h1>
<table>
    <thead>
       <tr>
          <th>ID</th> 
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Mount Point</th>
          <th>Total</th>
          <th>Used</th>
          <th>Free</th>
          <th>Percent</th>
       </tr>
    </thead>
    
    <tbody>
       {% for row in disk_stats %}
          <tr>
             <td>{{ row.id }}</td>
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.mount_point }}</td>
             <td>{{ row.total }}</td>
             <td>{{ row.used }}</td>
             <td>{{ row.free }}</td>
             <td>{{ row.percent }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
{% endblock %}

app/templates/index.html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/static/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" href="/static/logo192.png"/><link rel="manifest" href="/static/manifest.json"/><title>React App</title><script defer="defer" src="/static/js/main.364fdfc9.js"></script><link href="/static/css/main.e6c13ad2.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

app/templates/memory.html
{% extends "index.html" %}
{% block content %}
<h1>Agent Memory Information</h1>
<table>
    <thead>
       <tr>
          <th>ID</th> 
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Active</th>
          <th>Available</th>
          <th>Free</th>
          <th>Inactive</th>
          <th>Percent</th>
          <th>Total</th>
          <th>Used</th>
          <th>Wired</th>
       </tr>
    </thead>
    
    <tbody>
       {% for row in memory_stats %}
          <tr>
             <td>{{ row.id }}</td>
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.active }}</td>
             <td>{{ row.available }}</td>
             <td>{{ row.free }}</td>
             <td>{{ row.inactive }}</td>
             <td>{{ row.percent }}</td>
             <td>{{ row.total }}</td>
             <td>{{ row.used }}</td>
             <td>{{ row.wired }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
{% endblock %}

app/templates/network.html
{% extends "index.html" %}
{% block content %}
<h1>Agent Network Information</h1>
<table>
    <thead>
       <tr>
          <th>ID</th> 
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Bytes Sent</th>
          <th>Bytes Received</th>
          <th>Packets Sent</th>
          <th>Packets Received</th>
          <th>Error Packets In</th>
          <th>Error Packets Out</th>
          <th>Dropped Packets In</th>
          <th>Dropped Packets Out</th>
       </tr>
    </thead>
    <tbody>
       {% for row in network_stats %}
          <tr>
             <td>{{ row.id }}</td> 
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.bytes_sent }}</td>
             <td>{{ row.bytes_recvd }}</td>
             <td>{{ row.packets_sent }}</td>
             <td>{{ row.packets_recvd }}</td>
             <td>{{ row.err_pkt_in }}</td>
             <td>{{ row.err_pkt_out }}</td>
             <td>{{ row.dropped_pkt_in }}</td>
             <td>{{ row.dropped_pkt_out }}</td>
          </tr>
       {% endfor %}
    </tbody>
</table>
<br>
<h3>Network IP Addresses</h3>
<table>
   <thead>
      <tr>
         <th>ID</th>
         <th>Timestamp</th>
         <th>Report ID</th>
         <th>Target</th>
         <th>IP Addresses</th>
      </tr>
   </thead>
   <tbody>
      {% for row in network_ips %}
         <tr>
            <td>{{ row.id }}</td> 
            <td>{{ row.timestamp }}</td>
            <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
            <td>{{ row.target }}</td>
            <td>{{ row.addresses }}</td>
         </tr>
      {% endfor %}
   </tbody>
</table>
{% endblock %}

app/templates/reports.html
{% extends "index.html" %}
{% block content %}
<h1>Agent Reports</h1>
<table>
    <thead>
       <tr> 
          <th>ID</th> 
          <th>Report ID</th>
          <th>User ID</th>
          <th>Timestamp</th>
          <th>Email</th>
          <th>Target</th>
       </tr>
    </thead>
    
    <tbody>
       {% for row in reports %}
          <tr>
             <td>{{ row.id }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.user_id }}</td>
             <td>{{ row.timestamp }}</td>
             <td>{{ row.email }}</td>
             <td>{{ row.target }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
{% endblock %}

app/templates/system.html
{% extends "index.html" %}
{% block content %}
<h1>Agent System Information</h1>
<h3>System Users</h3>
<table>
    <thead>
       <tr>
          <th>ID</th>
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Started</th>
          <th>Terminal</th>
          <th>Username</th>
       </tr>
    </thead>
    
    <tbody>
       {% for row in system_users %}
          <tr>
             <td>{{ row.id }}</td> 
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.started }}</td>
             <td>{{ row.terminal }}</td>
             <td>{{ row.username }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
 <br>
 <h3>System Uptimes</h3>
 <table>
    <thead>
       <tr>
          <th>ID</th> 
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Uptime</th>
       </tr>
    </thead>
    <tbody>
       {% for row in system_uptime %}
          <tr>
             <td>{{ row.id }}</td>
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.uptime }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
 <br>
 <h3>Operating Systems</h3>
 <table>
    <thead>
       <tr>
          <th>ID</th> 
          <th>Timestamp</th>
          <th>Report ID</th>
          <th>Target</th>
          <th>Operating System</th>
       </tr>
    </thead>
    <tbody>
       {% for row in system_os %}
          <tr>
             <td>{{ row.id }}</td> 
             <td>{{ row.timestamp }}</td>
             <td><a href="{{ url_for('base_print.report_details', report_id=row.report_id) }}">{{ row.report_id }}</a></td>
             <td>{{ row.target }}</td>
             <td>{{ row.opersys }}</td>
          </tr>
       {% endfor %}
    </tbody>
 </table>
{% endblock %}